<?php
return array(
	'employee' => 'fa-user',
	'attendance' => 'fa-book',
	'leave' => 'fa-coffee',
	'payroll' => 'fa-money',
	'task' => 'fa-tasks',
	'holiday' => 'fa-fighter-jet',
	'ticket' => 'fa-ticket',
	'expense' => 'fa-credit-card',
	'award' => 'fa-trophy',
	'announcement' => 'fa-list-alt',
	'job' => 'fa-bullhorn',
	'message' => 'fa-envelope',
	'department' => 'fa-sitemap',
	'designation' => 'fa-user-secret',
	'configuration' => 'fa-cogs',
	'custom-field' => 'fa-clone',
	'template' => 'fa-envelope',
	'language' => 'fa-globe',
	'mail-configuration' => 'fa-envelope',
	'permission' => 'fa-unlock',
	'authentication' => 'fa-sign-in',
	'login' => 'fa-sign-in',
	'logout' => 'fa-sign-out',
	'change-password' => 'fa-key',
	'to-do' => 'fa-list',
	'logo' => 'fa-image',
	'salary' => 'fa-credit-card',
	'office-shift' => 'fa-clock-o',
	'contract' => 'fa-pencil',
	'document' => 'fa-file-o',
	'api' => 'fa-ellipsis-h',
	'clock' => 'fa-clock-o',
	);