<?php
return array(
'manage_language' => 'language',
'change_language' => 'language',
'list_department' => 'department',
'create_department' => 'department',
'edit_department' => 'department',
'delete_department' => 'department',
'list_designation' => 'designation',
'create_designation' => 'designation',
'edit_designation' => 'designation',
'delete_designation' => 'designation',
'manage_all_designation' => 'designation',
'manage_subordinate_designation' => 'designation',
'manage_custom_field' => 'custom_field',
'manage_template' => 'template',
'manage_message' => 'message',
'list_holiday' => 'holiday',
'create_holiday' => 'holiday',
'edit_holiday' => 'holiday',
'delete_holiday' => 'holiday',
'list_employee' => 'employee',
'create_employee' => 'employee',
'edit_employee' => 'employee',
'delete_employee' => 'employee',
'manage_all_employee' => 'employee',
'manage_subordinate_employee' => 'employee',
'manage_configuration' => 'configuration',
'list_expense' => 'expense',
'create_expense' => 'expense',
'edit_expense' => 'expense',
'delete_expense' => 'expense',
'manage_all_expense' => 'expense',
'manage_subordinate_expense' => 'expense',
'change_expense_status' => 'expense',
'list_announcement' => 'announcement',
'create_announcement' => 'announcement',
'edit_announcement' => 'announcement',
'delete_announcement' => 'announcement',
'manage_all_announcement' => 'announcement',
'manage_subordinate_announcement' => 'announcement',
'list_award' => 'award',
'create_award' => 'award',
'edit_award' => 'award',
'delete_award' => 'award',
'manage_all_award' => 'award',
'manage_subordinate_award' => 'award',
'list_task' => 'task',
'create_task' => 'task',
'manage_all_task' => 'task',
'manage_subordinate_task' => 'task',
'edit_task' => 'task',
'delete_task' => 'task',
'update_task_progress' => 'task',
'assign_task' => 'task',
'list_ticket' => 'ticket',
'create_ticket' => 'ticket',
'edit_ticket' => 'ticket',
'delete_ticket' => 'ticket',
'manage_all_ticket' => 'ticket',
'manage_subordinate_ticket' => 'ticket',
'update_ticket_status' => 'ticket',
'assign_ticket' => 'ticket',
'request_leave' => 'leave',
'edit_leave' => 'leave',
'delete_leave' => 'leave',
'manage_all_leave' => 'leave',
'manage_subordinate_leave' => 'leave',
'update_leave_status' => 'leave',
'update_profile' => 'employee',
'update_attendance' => 'attendance',
'generate_payroll' => 'payroll',
'list_job' => 'job',
'create_job' => 'job',
'edit_job' => 'job',
'delete_job' => 'job',
'manage_all_job' => 'job',
'manage_subordinate_job' => 'job',
'manage_job_application' => 'job',
'reset_employee_password' => 'employee',
'message_all_employee' => 'message',
'message_subordinate' => 'message',
'manage_email_log' => 'system',
'manage_backup' => 'system',

'appraisal_user'=>'appraisal',
'appraisal_user_edit'=>'appraisal',
'appraisal_user_edit_save'=>'appraisal',
'appraisal_user_view'=>'appraisal',

'appraisal_rating'=>'appraisal_rating',
'appraisal_rating_edit'=>'appraisal_rating',
'appraisal_rating_edit_save'=>'appraisal_rating',
'appraisal_rating_view'=>'appraisal_rating',

'appraisal_task_add'=>'appraisal_rating',
'appraisal_task_edit'=>'appraisal_rating',
'appraisal_task_edit_save'=>'appraisal_rating',
'appraisal_task_update'=>'appraisal_rating',

'appraisal_review'=>'appraisal_review',
'appraisal_review_edit'=>'appraisal_review',
'appraisal_review_edit_save'=>'appraisal_review',
'appraisal_review_view'=>'appraisal_review',

'supervisor_list'=>'supervisor',
'supervisor_add'=>'supervisor',
'supervisor_delete'=>'supervisor',
'supervisor_employee'=>'supervisor',
'supervisor_employee_add'=>'supervisor',


);

